services:
  mysql-messenger-client-2:
    image: mysql:8.0
    hostname: mysql-messenger-client-2
    environment:
      - MYSQL_DATABASE=Messenger-Client-2
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "3322:3306"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-pP@ssw0rd" ]
      interval: 10s
      retries: 5
      timeout: 5s

  messenger-client-2:
    build:
      context: ./  # Contexto del Dockerfile
    container_name: messenger-client-2
    ports:
      - "8082:8092"
    networks:
      - backend-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-messenger-client-2:3306/Messenger-Client-2?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    depends_on:
      mysql-messenger-client-2:
        condition: service_healthy
    entrypoint:
      [
        "./wait-for-it.sh", "eureka-server:8761", "-t", "60", "--",
        "./wait-for-it.sh", "mysql-messenger-client-2:3306", "-t", "60", "--",
        "java", "-jar", "/app/messenger-client-2.jar"
      ]

networks:
  backend-network:
    external: true
